# Generated by Django 5.2.7 on 2025-10-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allergy_app.fooditem'),
        ),
    ]
