# Generated by Django 5.2.7 on 2025-10-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergy_app', '0002_alter_scanhistory_food_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
